import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dictionaries, formatMessage, uiMessage, uiError, messageText, messageDescriptor, withMessageDetail } from '../src/localization.mjs'
import { activeLocale, installArenaLocale, subscribeLocale, translate } from '../src/client/locale-store.mjs'
import { normalizeRoomWorkdir } from '../src/workspace.mjs'
import { parseSpeechDirectives } from '../src/shared.mjs'

test('Chinese and English dictionaries have complete matching keys and placeholders', () => {
  assert.deepEqual(Object.keys(dictionaries.zh).sort(), Object.keys(dictionaries.en).sort())
  const placeholders = text => [...text.matchAll(/\{(\w+)\}/g)].map(m => m[1]).sort()
  for (const key of Object.keys(dictionaries.zh)) {
    assert.ok(dictionaries.zh[key].trim(), key)
    assert.ok(dictionaries.en[key].trim(), key)
    assert.deepEqual(placeholders(dictionaries.zh[key]), placeholders(dictionaries.en[key]), key)
  }
})

test('all literal translation references resolve to a dictionary entry', () => {
  for (const file of ['src/client/index.tsx', 'src/index.mjs', 'src/shared.mjs', 'src/workspace.mjs']) {
    const source = readFileSync(new URL('../' + file, import.meta.url), 'utf8')
    for (const match of source.matchAll(/\b(?:t|notice|uiMessage)\(\s*['"]([^'"]+)['"]/g)) {
      assert.ok(Object.hasOwn(dictionaries.zh, match[1]), `${file}: ${match[1]}`)
    }
  }
  const source = readFileSync(new URL('../src/client/i18n.ts', import.meta.url), 'utf8')
  for (const match of source.matchAll(/(?:name|description): '([^']+)'/g)) assert.ok(dictionaries.zh[match[1]], match[1])
})

test('native locale subscription updates immediately and never writes preferences', () => {
  const dicts = new Map(), callbacks = new Set()
  let selected = 'en', notifications = 0
  const service = {
    getLocale: () => ({ active: selected }),
    register(ns, lang, dict) { dicts.set(`${ns}:${lang}`, dict); return () => dicts.delete(`${ns}:${lang}`) },
    bind(ns) { return (key, params) => {
      assert.ok(dicts.has(`${ns}:${selected}`))
      return formatMessage(key, params, selected)
    } },
    subscribe(fn) { callbacks.add(fn); return () => callbacks.delete(fn) },
    setLocale() { throw new Error('Arena must not write native language settings') },
  }
  const off = subscribeLocale(() => notifications++)
  const dispose = installArenaLocale(service)
  assert.equal(activeLocale(), 'en')
  assert.equal(translate('counts.members', { count: 4 }), '4 group members')
  selected = 'zh'
  for (const callback of callbacks) callback()
  assert.equal(translate('counts.members', { count: 4 }), '4 位群成员')
  assert.equal(notifications, 2)
  dispose(); off()
  assert.equal(callbacks.size, 0)
  assert.equal(dicts.size, 0)
})

test('system descriptors preserve names, paths, and original text without translating user content', () => {
  const path = 'D:\\用户项目\\{p1}\\test.txt'
  const message = uiMessage('workspace.the.working.directory.is.not.a.directory.value', { p0: path })
  assert.equal(messageText(message), `工作区不是目录：${path}`)
  const descriptor = messageDescriptor(message)
  assert.equal(formatMessage(descriptor.key, descriptor.params, 'en'), `The working directory is not a directory: ${path}`)
  assert.equal(messageDescriptor('用户自己写的普通消息'), undefined)
  const detailed = withMessageDetail(uiMessage('toolactivity.using.value', { p0: 'read_file' }), path)
  assert.equal(messageText(detailed), `正在使用 read_file：${path}`)
  assert.equal(messageDescriptor(detailed).suffix, `：${path}`)
})

test('workspace errors carry an English-renderable descriptor and the original error status', async () => {
  await assert.rejects(normalizeRoomWorkdir('relative/path'), error => {
    assert.equal(error.status, 400)
    assert.ok(error.i18n)
    assert.match(formatMessage(error.i18n.key, error.i18n.params, 'en'), /absolute directory/)
    return true
  })
  const error = uiError(uiMessage('workspace.the.chat.name.cannot.be.empty'), 400, TypeError)
  assert.ok(error instanceof TypeError)
  assert.equal(error.message, '聊天名称不能为空')
})

test('English mute and unmute commands generated by the interface remain functional', () => {
  const users = [{ id: 'alice', name: 'Alice' }, { id: 'b', name: '从雨' }]
  assert.deepEqual(parseSpeechDirectives('@Alice stop talking', users).muteIds, ['alice'])
  const unmute = parseSpeechDirectives('@Alice you can speak again', users)
  assert.deepEqual(unmute.unmuteIds, ['alice'])
  assert.equal(unmute.commandOnly, true)
  assert.deepEqual(parseSpeechDirectives('Everyone, stop replying', users).muteIds.sort(), ['alice', 'b'])
})
